#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTPB,           sensorI2CCustom9V)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool getXY(int &Xbuf, int &Ybuf)
{
	int const replySize = 1;
	char send[3] = {2, 0x10, 128};
	char send2[3] = {2, 0x10, 136};
	char packet[1];
	for (int i = 0; i < 2; i++)
	{
		if (i == 0)
		{
			sendI2CMsg(HTPB, send, replySize);
			sleep(200);
			readI2CReply(HTPB, packet, replySize);
			Ybuf = packet;
		}
		else
		{
			sendI2CMsg(HTPB, send2, replySize);
			sleep(200);
			readI2CReply(HTPB, packet, replySize);
			if(Xbuf != packet)
			{
				Xbuf = packet;
				return true;
			}
		}
	}
	return false;
}

void turn(int Lspeed, int Rspeed, int time)
{
	motor[motorD] = Lspeed;
	motor[motorE] = Lspeed;
	motor[motorF] = Rspeed;
	motor[motorG] = Rspeed;
	sleep(time);
	motor[motorD] = 0;
	motor[motorE] = 0;
	motor[motorF] = 0;
	motor[motorG] = 0;
}

task main()
{
	int j = 0;
	int Xpoint = 0, Ypoint = 0;
	int motorspd = 255;
	while(j <= 2)
	{
		//turn to center goal
		if(getXY(Ypoint, Xpoint))
		{
			eraseDisplay();
			displayTextLine(1, "%d", Xpoint);
			drawCircle(Xpoint/2.65625 - 2, Ypoint/7.0833 + 2, 4);
			motorspd = Xpoint - 130;
			motor[motorD] = motorspd;
			motor[motorE] = motorspd;
			motor[motorF] = -motorspd;
			motor[motorG] = -motorspd;
			sleep(20);
			motor[motorD] = 0;
			motor[motorE] = 0;
			motor[motorF] = 0;
			motor[motorG] = 0;
		}
		else if(abs(motorspd) < 10)
		{
			j++;
		}
	}
	motor[motorD] = 0;
	motor[motorE] = 0;
	motor[motorF] = 0;
	motor[motorG] = 0;
	getXY(Ypoint, Xpoint);
	turn(20, 20, Ypoint * 20);
	sleep(500);
	motor[motorH] = -100;
	sleep(1500);
	motor[motorH] = 0;
	motor[motorI] = -50;
	sleep(1000);
	motor[motorH] = 100;
	sleep(1000);
	turn(20, -20, 1000);

}

///////////////////mem map////////////////////////////
//SharedMem01 = 128
//SharedMem02 = 132
//SharedMem03 = 136
//SharedMem04 = 140
//SharedMem32 = 252
//each mem is 32 bit
//
//
