#pragma config(Sensor, S1,     protoBoard,     sensorI2CCustom9V)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "hitechnic-protoboard.h"

task main()
{
	byte send = 0x4C;
	char breply[1];
	while (true)
	{
		sendI2CMsg(S1, &send, 1);
		readI2CReply(S1, breply, 1);
		displayTextLine(3, "%d", breply);
		wait1Msec(500);
	}
}
