#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     motorH,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c";

int expDrive (int joyVal, float driveExp, int joyDead, int motorMin){
	int joyMax = 128 - joyDead;
	int joySign = sgn(joyVal);
	int temp = abs(joyVal);
	int joyLive = abs(temp - joyDead);
	int fine = (joySign * (motorMin + ((100 - motorMin) * (pow(joyLive, driveExp) / pow(joyMax, driveExp)))));
	return fine;
}

task main()
{
	nMotorPIDSpeedCtrl[motorD] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[motorE] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[motorF] = mtrSpeedReg;
	nMotorPIDSpeedCtrl[motorG] = mtrSpeedReg;
	nMotorEncoder[motorD] = 0;
	nMotorEncoder[motorE] = 0;
	nMotorEncoder[motorF] = 0;
	nMotorEncoder[motorG] = 0;

	int pMotorMin = 0;
	int pJoyDead = 7;
	float pDriveExp = 1.7;
	playSoundFile("Bang.rso");
	int servoVal = 0;
	// 1 = down, 0 = up

	while(true){
		getJoystickSettings(joystick);
		if (joy1Btn(2) == 1){
			if (servoVal == 1){
				servo[servo4] = 255;
				servo[servo6] = 0;
				servoVal = 0;
				writeDebugStreamLine("servo down");
				wait1Msec(500);
				} else {
				servo[servo4] = 128;
				servo[servo6] = 128;
				servoVal = 1;
				writeDebugStreamLine("servo up");
				wait1Msec(500);
			}
		}

		//lift and sweeper
		if (joystick.joy1_TopHat == -1){
			// lift stop, up, down
			//writeDebugStreamLine("Nothing Pressed");
			//wait1Msec(50);
			motor[motorH] = 0;
			motor[motorI] = 0;
			} else {
			if (joystick.joy1_TopHat == 0){
				motor[motorI] = 40;
				//writeDebugStreamLine("Lift up");
				//wait1Msec(50);
				} else {
				if (joystick.joy1_TopHat == 4){
					motor[motorI] = -40;
					//writeDebugStreamLine("Lift down");
					//wait1Msec(50);
					} else {
					// sweeper pick, release
					if (joystick.joy1_TopHat == 6){
						motor[motorH] = 70;
						} else {
						if (joystick.joy1_TopHat == 2){
							motor[motorH] = -70;
						}
					}
				}
			}
		}

	if ((joy1Btn(5) == 0) && (joy1Btn(6) == 0)){
		motor[motorD] = (0.2)*(expDrive(joystick.joy1_y1, pDriveExp, pJoyDead, pMotorMin));
		motor[motorE] = (0.2)*(expDrive(joystick.joy1_y1, pDriveExp, pJoyDead, pMotorMin));
		motor[motorF] = (0.2)*(expDrive(joystick.joy1_y2, pDriveExp, pJoyDead, pMotorMin));
		motor[motorG] = (0.2)*(expDrive(joystick.joy1_y2, pDriveExp, pJoyDead, pMotorMin));
		writeDebugStreamLine("Encoder d: %d", nMotorEncoder[motorD]);
		} else{
		// logic here needs to be fixed
		if (joy1Btn(5) == 1){
			//motor[motorD] = (0.78)*(expDrive(joystick.joy1_y1, pDriveExp, pJoyDead, pMotorMin));
			//motor[motorE] = (0.78)*(expDrive(joystick.joy1_y1, pDriveExp, pJoyDead, pMotorMin));
			//motor[motorF] = (0.78)*(expDrive(joystick.joy1_y2, pDriveExp, pJoyDead, pMotorMin));
			//motor[motorG] = (0.78)*(expDrive(joystick.joy1_y2, pDriveExp, pJoyDead, pMotorMin));

			motor[motorD] = (0.68)*(expDrive(joystick.joy1_y1, pDriveExp, pJoyDead, pMotorMin));
			motor[motorE] = (0.68)*(expDrive(joystick.joy1_y1, pDriveExp, pJoyDead, pMotorMin));
			motor[motorF] = (0.68)*(expDrive(joystick.joy1_y2, pDriveExp, pJoyDead, pMotorMin));
			motor[motorG] = (0.68)*(expDrive(joystick.joy1_y2, pDriveExp, pJoyDead, pMotorMin));

		}
		if (joy1Btn(6) == 1){
			motor[motorD] = (0.68)*(expDrive(joystick.joy1_y1, pDriveExp, pJoyDead, pMotorMin));
			motor[motorE] = (0.68)*(expDrive(joystick.joy1_y1, pDriveExp, pJoyDead, pMotorMin));
			motor[motorF] = (0.68)*(expDrive(joystick.joy1_y2, pDriveExp, pJoyDead, pMotorMin));
			motor[motorG] = (0.68)*(expDrive(joystick.joy1_y2, pDriveExp, pJoyDead, pMotorMin));

			//motor[motorD] = (0.78)*(expDrive(joystick.joy1_y1, pDriveExp, pJoyDead, pMotorMin));
			//motor[motorE] = (0.78)*(expDrive(joystick.joy1_y1, pDriveExp, pJoyDead, pMotorMin));
			//motor[motorF] = (0.78)*(expDrive(joystick.joy1_y2, pDriveExp, pJoyDead, pMotorMin));
			//motor[motorG] = (0.78)*(expDrive(joystick.joy1_y2, pDriveExp, pJoyDead, pMotorMin));
		}
	}
}
}
